### PR TITLE
fix Sphinx documentation

### PR DESCRIPTION
**Pull request by Ptival**
The Sphinx documentation was outdated, using the pretty bad default layout, and also severely broken.

Before:
image

After:
image

### CODE REVIEW

**Comment by cuddihyge** [comment]
Thanks.  Will it auto-update in the future or have I been forgetting a step

**Comment by Ptival** [comment]
Do you mean on:
https://semtk-python3.readthedocs.io/en/latest/api/semtk3.html
?

If so, I guess there must be an extra step, but I'm not sure what. I will look into it.

**Comment by Ptival** [comment]
Hmm you might need to follow [some of these steps](https://docs.readthedocs.io/en/stable/integrations.html#github)?

I'm not sure how they got deployed in the first place if this was not set up already.

**Comment by Ptival** [comment]
I've obtained access (from Langston) to the `readthedocs` setup to launch the update, so it's now udpated at [this address](https://semtk-python3.readthedocs.io/en/latest/api/semtk3.html)

I'll try to set up the webhooks later so that we no longer need to trigger this manually.

**Pull request merged**
